module Color {
    interface IColor {
        aliceblue: string;
        antiquewhite: string;
        aqua: string;
        aquamarine: string;
        azure: string;
        beige: string;
        bisque: string;
        black: string;
        blanchedalmond: string;
        blue: string;
        blueviolet: string;
        brown: string;
        burlywood: string;
        cadetblue: string;
        chartreuse: string;
        chocolate: string;
        coral: string;
        cornflowerblue: string;
        cornsilk: string;
        crimson: string;
        cyan: string;
        darkblue: string;
        darkcyan: string;
        darkgoldenrod: string;
        darkgray: string;
        darkgrey: string;
        darkgreen: string;
        darkkhaki: string;
        darkmagenta: string;
        darkolivegreen: string;
        darkorange: string;
        darkorchid: string;
        darkred: string;
        darksalmon: string;
        darkseagreen: string;
        darkslateblue: string;
        darkslategray: string;
        darkslategrey: string;
        darkturquoise: string;
        darkviolet: string;
        deeppink: string;
        deepskyblue: string;
        dimgray: string;
        dimgrey: string;
        dodgerblue: string;
        firebrick: string;
        floralwhite: string;
        forestgreen: string;
        fuchsia: string;
        gainsboro: string;
        ghostwhite: string;
        gold: string;
        goldenrod: string;
        gray: string;
        grey: string;
        green: string;
        greenyellow: string;
        honeydew: string;
        hotpink: string;
        indianred: string;
        indigo: string;
        ivory: string;
        khaki: string;
        lavender: string;
        lavenderblush: string;
        lawngreen: string;
        lemonchiffon: string;
        lightblue: string;
        lightcoral: string;
        lightcyan: string;
        lightgoldenrodyellow: string;
        lightgray: string;
        lightgrey: string;
        lightgreen: string;
        lightpink: string;
        lightsalmon: string;
        lightseagreen: string;
        lightskyblue: string;
        lightslategray: string;
        lightslategrey: string;
        lightsteelblue: string;
        lightyellow: string;
        lime: string;
        limegreen: string;
        linen: string;
        magenta: string;
        maroon: string;
        mediumaquamarine: string;
        mediumblue: string;
        mediumorchid: string;
        mediumpurple: string;
        mediumseagreen: string;
        mediumslateblue: string;
        mediumspringgreen: string;
        mediumturquoise: string;
        mediumvioletred: string;
        midnightblue: string;
        mintcream: string;
        mistyrose: string;
        moccasin: string;
        navajowhite: string;
        navy: string;
        oldlace: string;
        olive: string;
        olivedrab: string;
        orange: string;
        orangered: string;
        orchid: string;
        palegoldenrod: string;
        palegreen: string;
        paleturquoise: string;
        palevioletred: string;
        papayawhip: string;
        peachpuff: string;
        peru: string;
        pink: string;
        plum: string;
        powderblue: string;
        purple: string;
        red: string;
        rosybrown: string;
        royalblue: string;
        saddlebrown: string;
        salmon: string;
        sandybrown: string;
        seagreen: string;
        seashell: string;
        sienna: string;
        silver: string;
        skyblue: string;
        slateblue: string;
        slategray: string;
        slategrey: string;
        snow: string;
        springgreen: string;
        steelblue: string;
        tan: string;
        teal: string;
        thistle: string;
        tomato: string;
        turquoise: string;
        violet: string;
        wheat: string;
        white: string;
        whitesmoke: string;
        yellow: string;
        yellowgreen: string;
    }

    export class Color implements IColor {

        aliceblue: string = "#f0f8ff";
        antiquewhite: string = "#faebd7";
        aqua: string = "#00ffff";
        aquamarine: string = "#7fffd4";
        azure: string = "#f0ffff";
        beige: string = "#f5f5dc";
        bisque: string = "#ffe4c4";
        black: string = "#000000";
        blanchedalmond: string = "#ffebcd";
        blue: string = "#0000ff";
        blueviolet: string = "#8a2be2";
        brown: string = "#a52a2a";
        burlywood: string = "#deb887";
        cadetblue: string = "#5f9ea0";
        chartreuse: string = "#7fff00";
        chocolate: string = "#d2691e";
        coral: string = "#ff7f50";
        cornflowerblue: string = "#6495ed";
        cornsilk: string = "#fff8dc";
        crimson: string = "#dc143c";
        cyan: string = "#00ffff";
        darkblue: string = "#00008b";
        darkcyan: string = "#008b8b";
        darkgoldenrod: string = "#b8860b";
        darkgray: string = "#a9a9a9";
        darkgrey: string = "#a9a9a9";
        darkgreen: string = "#006400";
        darkkhaki: string = "#bdb76b";
        darkmagenta: string = "#8b008b";
        darkolivegreen: string = "#556b2f";
        darkorange: string = "#ff8c00";
        darkorchid: string = "#9932cc";
        darkred: string = "#8b0000";
        darksalmon: string = "#e9967a";
        darkseagreen: string = "#8fbc8f";
        darkslateblue: string = "#483d8b";
        darkslategray: string = "#2f4f4f";
        darkslategrey: string = "#2f4f4f";
        darkturquoise: string = "#00ced1";
        darkviolet: string = "#9400d3";
        deeppink: string = "#ff1493";
        deepskyblue: string = "#00bfff";
        dimgray: string = "#696969";
        dimgrey: string = "#696969";
        dodgerblue: string = "#1e90ff";
        firebrick: string = "#b22222";
        floralwhite: string = "#fffaf0";
        forestgreen: string = "#228b22";
        fuchsia: string = "#ff00ff";
        gainsboro: string = "#dcdcdc";
        ghostwhite: string = "#f8f8ff";
        gold: string = "#ffd700";
        goldenrod: string = "#daa520";
        gray: string = "#808080";
        grey: string = "#808080";
        green: string = "#008000";
        greenyellow: string = "#adff2f";
        honeydew: string = "#f0fff0";
        hotpink: string = "#ff69b4";
        indianred: string = "#cd5c5c";
        indigo: string = "#4b0082";
        ivory: string = "#fffff0";
        khaki: string = "#f0e68c";
        lavender: string = "#e6e6fa";
        lavenderblush: string = "#fff0f5";
        lawngreen: string = "#7cfc00";
        lemonchiffon: string = "#fffacd";
        lightblue: string = "#add8e6";
        lightcoral: string = "#f08080";
        lightcyan: string = "#e0ffff";
        lightgoldenrodyellow: string = "#fafad2";
        lightgray: string = "#d3d3d3";
        lightgrey: string = "#d3d3d3";
        lightgreen: string = "#90ee90";
        lightpink: string = "#ffb6c1";
        lightsalmon: string = "#ffa07a";
        lightseagreen: string = "#20b2aa";
        lightskyblue: string = "#87cefa";
        lightslategray: string = "#778899";
        lightslategrey: string = "#778899";
        lightsteelblue: string = "#b0c4de";
        lightyellow: string = "#ffffe0";
        lime: string = "#00ff00";
        limegreen: string = "#32cd32";
        linen: string = "#faf0e6";
        magenta: string = "#ff00ff";
        maroon: string = "#800000";
        mediumaquamarine: string = "#66cdaa";
        mediumblue: string = "#0000cd";
        mediumorchid: string = "#ba55d3";
        mediumpurple: string = "#9370d8";
        mediumseagreen: string = "#3cb371";
        mediumslateblue: string = "#7b68ee";
        mediumspringgreen: string = "#00fa9a";
        mediumturquoise: string = "#48d1cc";
        mediumvioletred: string = "#c71585";
        midnightblue: string = "#191970";
        mintcream: string = "#f5fffa";
        mistyrose: string = "#ffe4e1";
        moccasin: string = "#ffe4b5";
        navajowhite: string = "#ffdead";
        navy: string = "#000080";
        oldlace: string = "#fdf5e6";
        olive: string = "#808000";
        olivedrab: string = "#6b8e23";
        orange: string = "#ffa500";
        orangered: string = "#ff4500";
        orchid: string = "#da70d6";
        palegoldenrod: string = "#eee8aa";
        palegreen: string = "#98fb98";
        paleturquoise: string = "#afeeee";
        palevioletred: string = "#d87093";
        papayawhip: string = "#ffefd5";
        peachpuff: string = "#ffdab9";
        peru: string = "#cd853f";
        pink: string = "#ffc0cb";
        plum: string = "#dda0dd";
        powderblue: string = "#b0e0e6";
        purple: string = "#800080";
        red: string = "#ff0000";
        rosybrown: string = "#bc8f8f";
        royalblue: string = "#4169e1";
        saddlebrown: string = "#8b4513";
        salmon: string = "#fa8072";
        sandybrown: string = "#f4a460";
        seagreen: string = "#2e8b57";
        seashell: string = "#fff5ee";
        sienna: string = "#a0522d";
        silver: string = "#c0c0c0";
        skyblue: string = "#87ceeb";
        slateblue: string = "#6a5acd";
        slategray: string = "#708090";
        slategrey: string = "#708090";
        snow: string = "#fffafa";
        springgreen: string = "#00ff7f";
        steelblue: string = "#4682b4";
        tan: string = "#d2b48c";
        teal: string = "#008080";
        thistle: string = "#d8bfd8";
        tomato: string = "#ff6347";
        turquoise: string = "#40e0d0";
        violet: string = "#ee82ee";
        wheat: string = "#f5deb3";
        white: string = "#ffffff";
        whitesmoke: string = "#f5f5f5";
        yellow: string = "#ffff00";
        yellowgreen: string = "#9acd32";


        constructor() {

        }
    }
}